services:

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3
    

  backend:
    build:
      context: ./backend
    container_name: backend_bewerbungsmaster
    restart: unless-stopped
    environment:
      DATABASE_URL_dev: ${DATABASE_URL_dev}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: frontend_bewerbungsmaster
    restart: unless-stopped
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_BASE_URL_prod}
      test_var: oarschloch
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  mysql_data: