name: Deploy Webapp

on:
  push:
    branches:
      - Tests

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh                
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa       
        ssh-keyscan -H "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts

    - name: Build and Run Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << EOF
          cd git_local/bewerbungsmaster
          git pull
          docker compose down || true
          docker compose up -d --build
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Pytests inside the container
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << EOF
          # Get the container ID or name
          container_id=$(docker ps -q --filter "name=backend_bewerbungsmaster")
          if [ -z "$container_id" ]; then
            echo "Error: No container found."
            exit 1
          fi
          # Run pytest inside the container
          docker exec -t "$container_id" bash -c "cd backend/tests && pytest tests.py"
        EOF
